In [2]:
import pandas as pd

In [3]:
#!pip install pandas

In [4]:
import numpy as np

In [5]:
np.arange(1,41).reshape((20,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30],
       [31, 32],
       [33, 34],
       [35, 36],
       [37, 38],
       [39, 40]])

In [6]:
df=pd.DataFrame(data=np.arange(1,41).reshape((20,2)),columns=["A","B"])

In [7]:
df.dtypes

A    int32
B    int32
dtype: object

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
df.head(8)

A   B
0   1   2
1   3   4
2   5   6
3   7   8
4   9  10
5  11  12
6  13  14
7  15  16

In [10]:
df.tail()

A   B
15  31  32
16  33  34
17  35  36
18  37  38
19  39  40

In [11]:
df.describe()

A         B
count  20.00000  20.00000
mean   20.00000  21.00000
std    11.83216  11.83216
min     1.00000   2.00000
25%    10.50000  11.50000
50%    20.00000  21.00000
75%    29.50000  30.50000
max    39.00000  40.00000

In [12]:
list(df.index)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [13]:
type(df["A"])

pandas.core.series.Series

In [14]:
# how to iterate the data with respect to row (loc)
df.loc[[0,4,5]] # write the row name in " " if the row is present in the string 


A   B
0   1   2
4   9  10
5  11  12

In [15]:
# column wise 
df.iloc[0:1,0:1]

A
0  1

In [16]:
df1=pd.DataFrame(np.random.randint(3,9,(5,6)))

In [17]:
df1

0  1  2  3  4  5
0  6  4  7  3  5  8
1  3  8  6  6  5  5
2  7  6  8  3  8  5
3  5  5  7  7  6  3
4  7  5  5  6  5  4

In [18]:
df1.iloc[:3,:2]

0  1
0  6  4
1  3  8
2  7  6

In [19]:
df1.iloc[:3,:2].values # convert into array

array([[6, 4],
       [3, 8],
       [7, 6]])

In [20]:
np.NaN   # null value or empty value

nan

In [21]:
df1.isnull()

0      1      2      3      4      5
0  False  False  False  False  False  False
1  False  False  False  False  False  False
2  False  False  False  False  False  False
3  False  False  False  False  False  False
4  False  False  False  False  False  False

In [22]:
df1.iloc[:3,:2]=np.nan

In [23]:
df1

0    1  2  3  4  5
0  NaN  NaN  7  3  5  8
1  NaN  NaN  6  6  5  5
2  NaN  NaN  8  3  8  5
3  5.0  5.0  7  7  6  3
4  7.0  5.0  5  6  5  4

In [24]:
df1.isnull()

0      1      2      3      4      5
0   True   True  False  False  False  False
1   True   True  False  False  False  False
2   True   True  False  False  False  False
3  False  False  False  False  False  False
4  False  False  False  False  False  False

In [25]:
df1.isnull().sum()

0    3
1    3
2    0
3    0
4    0
5    0
dtype: int64

In [26]:
df1.isnull().sum().sum()

6

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       20 non-null     int32
 1   B       20 non-null     int32
dtypes: int32(2)
memory usage: 292.0 bytes


In [28]:
df['A'].value_counts() #it always apply on the series data

A
1     1
3     1
37    1
35    1
33    1
31    1
29    1
27    1
25    1
23    1
21    1
19    1
17    1
15    1
13    1
11    1
9     1
7     1
5     1
39    1
Name: count, dtype: int64

In [29]:
df1[0].unique()

array([nan,  5.,  7.])

In [30]:
df1.nunique()

0    2
1    1
2    4
3    3
4    3
5    4
dtype: int64

In [31]:
df1.nunique(axis=1)

0    4
1    2
2    3
3    4
4    4
dtype: int64

In [32]:
df1[0]>3

0    False
1    False
2    False
3     True
4     True
Name: 0, dtype: bool

In [33]:
df1.to_csv("csvData.csv")

In [34]:
df1.to_csv("csvData.csv",index=False)

In [35]:
data_from_csv_file=pd.read_csv("csvData.csv")
data_from_csv_file

0    1  2  3  4  5
0  NaN  NaN  7  3  5  8
1  NaN  NaN  6  6  5  5
2  NaN  NaN  8  3  8  5
3  5.0  5.0  7  7  6  3
4  7.0  5.0  5  6  5  4

In [36]:
df1.to_excel("data.xlsx")

In [37]:
#!pip install openpyxl