In [1]:
import numpy as np

In [5]:
 lst=[1,2,3]
 arr=np.array(lst)
 arr

array([1, 2, 3])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(3,)

In [10]:
arr1=np.array([[1,2,3],[4,5,6]])

In [11]:
arr1.shape

(2, 3)

In [14]:
arr2=np.reshape(arr1,newshape=(3,2))
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
arr2.shape

(3, 2)

In [16]:
arr3=np.reshape(arr1,newshape=(1,3,2))
arr3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [18]:
arr3[:,1,:]

array([[3, 4]])

In [19]:
arr3[0]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
np.arange(1,10)

(9,)

In [24]:
np.arange(1,11).reshape(5,2).shape

(5, 2)

In [27]:
 np.linspace(1,40,40).reshape(1,2,20)

array([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14., 15., 16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
         33., 34., 35., 36., 37., 38., 39., 40.]]])

In [29]:
np.zeros(20).reshape(1,2,10)

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [30]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.ones((3,5))+9

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [32]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
#Generating the random values in numpy arrays
print("Random number(uniform distribution)")
random_array=np.random.rand(2,4)
random_array



Random number(uniform distribution)


array([[0.65503948, 0.09221337, 0.05654387, 0.28917625],
       [0.45437373, 0.37788682, 0.92080052, 0.53490152]])

In [35]:
print("Random number following a Normal distribution m=0 , std=1")
normal_dis_array=np.random.randn(2,4)
normal_dis_array

Random number following a Normal distribution m=0 , std=1


array([[ 0.34057688, -1.2374486 ,  1.9067324 , -1.18409433],
       [-0.01076368, -0.35210481, -0.65186054, -0.77581545]])

In [37]:
normal_dis_array.mean(axis=1)

array([-0.04355841, -0.44763612])

In [53]:
print(" integer number")
np.random.randint(1,10,10)

 integer number


array([1, 8, 9, 2, 7, 8, 1, 7, 7, 9])

In [54]:
print(" integer number")
np.random.randint(1,10,size=(2,10))

 integer number


array([[4, 9, 5, 1, 3, 1, 2, 2, 8, 4],
       [5, 5, 2, 3, 3, 6, 5, 3, 9, 7]])

In [57]:
arr1=np.random.randint(1,50,size=(5,6))

In [58]:
arr1

array([[23, 12,  5,  4, 45, 38],
       [25,  8,  5, 27, 38, 34],
       [ 5, 38, 45, 24,  4, 27],
       [ 7,  6, 20, 17, 27, 18],
       [23, 30, 38,  3, 27,  6]])

In [59]:
arr1[:,:3]

array([[23, 12,  5],
       [25,  8,  5],
       [ 5, 38, 45],
       [ 7,  6, 20],
       [23, 30, 38]])

In [61]:
arr1[3:,3:]

array([[17, 27, 18],
       [ 3, 27,  6]])

In [62]:
arr1[2:4,1:3]

array([[38, 45],
       [ 6, 20]])

In [63]:
#univarsal function
arr_m=np.random.randint(1,20,(3,3))
arr_n=np.random.randint(2,5,(3,3))

In [64]:
arr_m/arr_n

array([[3.  , 2.  , 3.5 ],
       [4.25, 4.75, 5.  ],
       [2.75, 5.  , 3.5 ]])

In [65]:
np.sqrt(arr_n)

array([[2.        , 2.        , 2.        ],
       [2.        , 2.        , 1.41421356],
       [2.        , 1.41421356, 2.        ]])

In [66]:
np.exp(arr_n)

array([[54.59815003, 54.59815003, 54.59815003],
       [54.59815003, 54.59815003,  7.3890561 ],
       [54.59815003,  7.3890561 , 54.59815003]])

In [67]:
np.log(arr_m)

array([[2.48490665, 2.07944154, 2.63905733],
       [2.83321334, 2.94443898, 2.30258509],
       [2.39789527, 2.30258509, 2.63905733]])

In [68]:
arr12=np.arange(1,20)

In [69]:
arr12

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [70]:
arr12[5:]=34

In [71]:
arr12

array([ 1,  2,  3,  4,  5, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
       34, 34])